<?php

namespace App\Database\Seeds;

use CodeIgniter\I18n\Time;

class UserSeeder extends \CodeIgniter\Database\Seeder
{
  public function run()
  {
    $data = [
      [
        'username'       => 'Kepala Desa',
        'password'       => md5('Kepala Desa'),
        'nama_lengkap'   => 'Setiadi, S.Pd',
        'email'          => '-',
        'level'          => 'user',
        'alamat'         => 'Dukuh Kalisalak RT 01/ RW 01, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '085600007095',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 1,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
      [
        'username'       => 'Sekretaris Desa',
        'password'       => md5('Sekretaris Desa'),
        'nama_lengkap'   => 'Kuntara',
        'email'          => 'Kuntorodila@gmail.com',
        'level'          => 'admin',
        'alamat'         => 'Dukuh Kalisalak RT 01/ RW 01, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '081391891992',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 2,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
      [
        'username'       => 'Kaur Umum',
        'password'       => md5('Kaur Umum'),
        'nama_lengkap'   => 'Bambang Sutrimo',
        'email'          => 'Sutrimobambang@gmail.com',
        'level'          => 'admin',
        'alamat'         => 'Dukuh Kalisalak RT 01/ RW 01, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '085351299990',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 3,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
      [
        'username'       => 'Kaur Keuangan',
        'password'       => md5('Kaur Keuangan'),
        'nama_lengkap'   => 'Sri Purwati',
        'email'          => 'Sripurwanti75838@gmail.com',
        'level'          => 'user',
        'alamat'         => 'Dukuh Pagotan RT 03/ RW 03, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '081391891435',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 4,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
      [
        'username'       => 'Kaur Perencanaan',
        'password'       => md5('Kaur Perencanaan'),
        'nama_lengkap'   => 'Ahmad Zamroni',
        'email'          => 'Zamronia318@gmail.com',
        'level'          => 'user',
        'alamat'         => 'Dukuh Gumingsir RT 03/ RW 04, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '085229034829',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 5,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
      [
        'username'       => 'Kasi Kesejahteraan',
        'password'       => md5('Kasi Kesejahteraan'),
        'nama_lengkap'   => 'Aminudin',
        'email'          => '-',
        'level'          => 'user',
        'alamat'         => 'Dukuh Kalisalak RT 04/ RW 01, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '081326933119',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 6,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
      [
        'username'       => 'Kasi Pemerintahan',
        'password'       => md5('Kasi Pemerintahan'),
        'nama_lengkap'   => 'Sirojut Tolibin',
        'email'          => 'Yaqindinal@gmail.com',
        'level'          => 'user',
        'alamat'         => 'Dukuh Kalisalak RT 01/ RW 01, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '082325139782',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 7,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
      [
        'username'       => 'Kasi Pelayanan',
        'password'       => md5('Kasi Pelayanan'),
        'nama_lengkap'   => "Arif Ma'ruf'",
        'email'          => 'Arifmaruffans@gmail.com',
        'level'          => 'user',
        'alamat'         => 'Dukuh Kalisalak RT 03/ RW 01, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '082329182684',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 8,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
      [
        'username'       => 'KepalaDusun1',
        'password'       => md5('KepalaDusun1'),
        'nama_lengkap'   => 'Hasan',
        'email'          => '-',
        'level'          => 'user',
        'alamat'         => 'Dukuh Kalisalak RT 01/ RW 01, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '085227611544',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 9,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
      [
        'username'       => 'KepalaDusun2',
        'password'       => md5('KepalaDusun2'),
        'nama_lengkap'   => 'Abd kholiq',
        'email'          => '-',
        'level'          => 'user',
        'alamat'         => 'Dukuh Kalibening RT 01/ RW 02, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '085293669302',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 9,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
      [
        'username'       => 'KepalaDusun3',
        'password'       => md5('KepalaDusun3'),
        'nama_lengkap'   => 'Sucipto',
        'email'          => '-',
        'level'          => 'user',
        'alamat'         => 'Dukuh Pagotan RT 03/ RW 03, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '082322638766',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 9,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
      [
        'username'       => 'KepalaDusun4',
        'password'       => md5('KepalaDusun4'),
        'nama_lengkap'   => 'Sunardi',
        'email'          => '-',
        'level'          => 'user',
        'alamat'         => 'Dukuh Gumingsir RT 04/ RW 04, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '085742825944',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 9,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
      [
        'username'       => 'KepalaDusun5',
        'password'       => md5('KepalaDusun5'),
        'nama_lengkap'   => 'Karno',
        'email'          => '-',
        'level'          => 'user',
        'alamat'         => 'Dukuh Kesemen RT 01/ RW 05, Desa Kalisalak, Kecamatan Limpung, Kabupaten Batang, Jawa Tengah. Kode Pos 51271',
        'telepon'        => '085640269666',
        'foto_profil'    => 'default.png',
        'id_bagian'      => 9,
        'usercreated_at' => Time::now(),
        'userupdated_at' => Time::now(),
      ],
    ];

      // Using Query Builder
      $this->db->table('tbl_user')->insertBatch($data);
  }
}